Update README.md
Elive/elive-for-servers pull request #4
Opened 2021-12-04 08:51 UTC by triantares

minor repairs to text.

2021-12-04 13:17 UTC, TheTechRobo requested changes

2021-12-04 13:17 UTC, TheTechRobo commented on README.md
> -**Install it** (from root):
I think "from root" is fine here, but that's my opinion.

2021-12-07 13:03 UTC, triantares commented
On Raspberry Pi php install fails on "php-gettext". It should be "php-php-gettext"

2021-12-07 15:24 UTC, closed without merging

2021-12-07 20:48 UTC, TheTechRobo commented
I agree - "from root" is just a shorter version of "from the root user", the latter being grammatically correct.